### ISSUE TITLE
Memory leak in Kseq.xs

### ISSUE THREAD

**Issue by sestaton** [cjfields/Bio-Kseq#1]
There is a memory leak (it appears to be in the XS code) that causes memory usage to increase as long as a file is being read.

**Comment by cjfields** [comment]
Yes, I can confirm that.  I'll see if I can track it down.

```
perl -MTest::Valgrind test.pl < test1_sanger.fastq 
1..15
# Using valgrind 3.8.1 located at /opt/local/bin/valgrind
# Using suppression file /Users/cjfields/.perl/Test-Valgrind/suppressions/1.13/memcheck-3.8.1-0eb5cfa81ba59d212d0871e7f5783b76.supp
ok 1 - InvalidFree
ok 2 - MismatchedFree
ok 3 - InvalidRead
ok 4 - InvalidWrite
ok 5 - InvalidJump
ok 6 - Overlap
ok 7 - InvalidMemPool
ok 8 - UninitCondition
ok 9 - UninitValue
ok 10 - SyscallParam
ok 11 - ClientCheck
not ok 12 - Leak_DefinitelyLost
#   Failed test 'Leak_DefinitelyLost'
#   at /Users/cjfields/perl5/perlbrew/perls/perl-5.16.1/lib/site_perl/5.16.1/darwin-2level/Test/Valgrind/Session.pm line 451.
#          got: 1
#     expected: 0
# 
#   163 bytes in 2 blocks are definitely lost in loss record 68 of 110
#     malloc (/opt/local/lib/valgrind/vgpreload_memcheck-amd64-darwin.so) [vg_replace_malloc.c:274]
#     Perl_savepv (/Users/cjfields/perl5/perlbrew/perls/perl-5.16.1/bin/perl) [?:?]
#     Perl_newXS_len_flags (/Users/cjfields/perl5/perlbrew/perls/perl-5.16.1/bin/perl) [?:?]
#     Perl_newCONSTSUB_flags (/Users/cjfields/perl5/perlbrew/perls/perl-5.16.1/bin/perl) [?:?]
#     Perl_gv_init_pvn (/Users/cjfields/perl5/perlbrew/perls/perl-5.16.1/bin/perl) [?:?]
#     Perl_gv_fetchpvn_flags (/Users/cjfields/perl5/perlbrew/perls/perl-5.16.1/bin/perl) [?:?]
#     Perl_gv_fetchsv (/Users/cjfields/perl5/perlbrew/perls/perl-5.16.1/bin/perl) [?:?]
#     Perl_ck_rvconst (/Users/cjfields/perl5/perlbrew/perls/perl-5.16.1/bin/perl) [?:?]
#     Perl_newUNOP (/Users/cjfields/perl5/perlbrew/perls/perl-5.16.1/bin/perl) [?:?]
#     Perl_yylex (/Users/cjfields/perl5/perlbrew/perls/perl-5.16.1/bin/perl) [?:?]
#     Perl_yyparse (/Users/cjfields/perl5/perlbrew/perls/perl-5.16.1/bin/perl) [?:?]
#     S_doeval (/Users/cjfields/perl5/perlbrew/perls/perl-5.16.1/bin/perl) [?:?]
ok 13 - Leak_IndirectlyLost
ok 14 - Leak_PossiblyLost
not ok 15 - Leak_StillReachable
#   Failed test 'Leak_StillReachable'
#   at /Users/cjfields/perl5/perlbrew/perls/perl-5.16.1/lib/site_perl/5.16.1/darwin-2level/Test/Valgrind/Session.pm line 451.
#          got: 1
#     expected: 0
# 
#   156 bytes in 1 blocks are still reachable in loss record 66 of 110
#     malloc (/opt/local/lib/valgrind/vgpreload_memcheck-amd64-darwin.so) [vg_replace_malloc.c:274]
#     malloc (/usr/lib/dyld) [?:?]
#     ImageLoaderMachOCompressed::instantiateFromFile(char const*, int, unsigned char const*, unsigned long long, unsigned long long, stat const&, unsigned int, unsigned int, linkedit_data_command const*, ImageLoader::LinkContext const&) (/usr/lib/dyld) [?:?]
#     ImageLoaderMachO::instantiateFromFile(char const*, int, unsigned char const*, unsigned long long, unsigned long long, stat const&, ImageLoader::LinkContext const&) (/usr/lib/dyld) [?:?]
#     dyld::loadPhase6(int, stat const&, char const*, dyld::LoadContext const&) (/usr/lib/dyld) [?:?]
#     dyld::loadPhase5(char const*, char const*, dyld::LoadContext const&, std::__1::vector<char const*, std::__1::allocator<char const*> >*) (/usr/lib/dyld) [?:?]
#     dyld::loadPhase4(char const*, char const*, dyld::LoadContext const&, std::__1::vector<char const*, std::__1::allocator<char const*> >*) (/usr/lib/dyld) [?:?]
#     dyld::loadPhase3(char const*, char const*, dyld::LoadContext const&, std::__1::vector<char const*, std::__1::allocator<char const*> >*) (/usr/lib/dyld) [?:?]
#     dyld::loadPhase1(char const*, char const*, dyld::LoadContext const&, std::__1::vector<char const*, std::__1::allocator<char const*> >*) (/usr/lib/dyld) [?:?]
#     dyld::loadPhase0(char const*, char const*, dyld::LoadContext const&, std::__1::vector<char const*, std::__1::allocator<char const*> >*) (/usr/lib/dyld) [?:?]
#     dyld::load(char const*, dyld::LoadContext const&) (/usr/lib/dyld) [?:?]
#     dyld::libraryLocator(char const*, bool, char const*, ImageLoader::RPathChain const*) (/usr/lib/dyld) [?:?]
# Looks like you failed 2 tests of 15.
# Looks like your test exited with 2 just after 15.
```

**Comment by cjfields** [comment]
Looks like the leak is due to the HV not being mortalized correctly.  Should be fixed in 4274145db3321278b8083471d633b76385d27c35

**Comment by sestaton** [comment]
I'm still seeing the same issue (memory usage goes from 800 MB to >7 GB reading a file of ~11 million sequences), though the test output shows just one test failing now.

```
perl -MTest::Valgrind bio_kseq.pl test.fastq.gz 
1..15
# Using valgrind 3.8.1 located at /usr/bin/valgrind
# Using suppression file /home/statonse/.perl/Test-Valgrind/suppressions/1.13/      memcheck-3.8.1-8dc0df351d1845585d70d94538af8c67.supp
ok 1 - InvalidFree
ok 2 - MismatchedFree
ok 3 - InvalidRead
ok 4 - InvalidWrite
ok 5 - InvalidJump
ok 6 - Overlap
ok 7 - InvalidMemPool
ok 8 - UninitCondition
ok 9 - UninitValue
ok 10 - SyscallParam
ok 11 - ClientCheck
ok 12 - Leak_DefinitelyLost
ok 13 - Leak_IndirectlyLost
ok 14 - Leak_PossiblyLost
not ok 15 - Leak_StillReachable
#   Failed test 'Leak_StillReachable'
#   at /home/statonse/perl5/perlbrew/perls/perl-5.14.2/lib/site_perl/5.14.2/x86_64-linux-thread-multi/Test/Valgrind/Session.pm line 451.
#          got: 1
#     expected: 0
# 
#   17 bytes in 1 blocks are still reachable in loss record 1 of 8
#     malloc (/usr/lib64/valgrind/vgpreload_memcheck-amd64-linux.so) [vg_replace_malloc.c:270]
#     _dl_map_object (/usr/lib64/ld-2.15.so) [?:?]
#     openaux (/usr/lib64/ld-2.15.so) [?:?]
#     _dl_catch_error (/usr/lib64/ld-2.15.so) [?:?]
#     _dl_map_object_deps (/usr/lib64/ld-2.15.so) [?:?]
#     dl_open_worker (/usr/lib64/ld-2.15.so) [?:?]
#     _dl_catch_error (/usr/lib64/ld-2.15.so) [?:?]
#     _dl_open (/usr/lib64/ld-2.15.so) [?:?]
#     dlopen_doit (/usr/lib64/libdl-2.15.so) [?:?]
#     _dl_catch_error (/usr/lib64/ld-2.15.so) [?:?]
#     _dlerror_run (/usr/lib64/libdl-2.15.so) [?:?]
#     dlopen@@GLIBC_2.2.5 (/usr/lib64/libdl-2.15.so) [?:?]
# Looks like you failed 1 test of 15.
# Looks like your test exited with 1 just after 15.
```

**Comment by cjfields** [comment]
Same here, but acc. to valgrind docs that particular error (Leak_StillReachable) isn't be a significant problem; note the error doesn't seem to involve perl and is 17 bytes.  Also, there is a nice note [here](http://stackoverflow.com/questions/11506370/valgrind-reports-unitialized-values-on-empty-c-program) regarding ld issues and valgrind, which may be something that should be added to the valgrind suppression file.

I'm running this on RHEL 6, using both perl 5.16.1 and perl 5.10.1 and don't see any memory issues via top.  Will test on my Macbook as well to confirm.

Can you maybe try a fresh download and test, or use `./Build realclean` or `git clean -fdx` prior to rebuilding?  

This is about halfway through my test run of 28M reads using perl 5.10.1, virt tops out around 120-130M:

<pre>
Tasks: 198 total,   3 running, 195 sleeping,   0 stopped,   0 zombie
Cpu(s): 25.6%us,  7.6%sy, 42.6%ni, 23.3%id,  0.0%wa,  0.0%hi,  0.9%si,  0.0%st
Mem:  16336632k total, 15301292k used,  1035340k free,    92848k buffers
Swap: 10305528k total,    30304k used, 10275224k free,  1234292k cached
  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND
 9479 cjfields  20   0  125m 4280 1944 R 100.0  0.0   1:41.76 perl test.pl /home/a-m/cjfields/.../18091326_GGCTAC_L003_R1_001.fastq.gz
 9490 cjfields  20   0 26024 1440 1048 R  1.8  0.0   0:00.01 top -u cjfields
</pre>

**Comment by cjfields** [comment]
Seems fine on Mac OS X 10.8.5 as well (perl 5.18.1).  Here's an htop screenshot, mem (virt, res, and system mem) stayed level during the run.

![image](https://f.cloud.github.com/assets/49265/1215431/cd5b1926-2664-11e3-8d2a-0ea3507c2af9.png)

**Comment by sestaton** [comment]
Thanks for the comments and the link. I just tested again, making sure I fetched that latest commits, and everything works fine (on Fedora 17 and RHEL 5.9 with perl 5.14.2). I think this issue appears to be resolved so I guess it can be closed unless you want to keep it open. Thanks for all the work on this!

**Comment by cjfields** [comment]
Cool, good to know it's working on your end.  Thanks for testing it out!
